# Generated by Django 5.1.3 on 2024-11-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='api_key',
            new_name='token',
        ),
    ]
